model:
  path: "/data/models/classifier"
  model: "yad_robot_basicnet_objects_111.model"
  class_map: "class_map_objects.json"
  net: "basicnet"
  activation: "softmax"  # softmax, sigmoid or None
  resize_size: 224

  ignore_robot: False  # sets shift_arm = True, if True
  shift_arm: False

