train:
  # gym
  steps_per_episode: 100
  episodes: 3600
  max_steps: ~

  ds_obj_mode: 1  # 0: objects
                  # 1: distractors
                  # 2: complete
  ds_sort_mode: 3  # 0: sorted, ascending
                   # 1: sorted, descending
                   # 2: sorted, custom
                   # 3: random
  custom_objs: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35]

  episodes_per_object: 1 # relevant for train_mode 1 or 2

  model_path: ~ # to continue training
  #model_path: "/home/ckorbach/nbv/next_best_view_rl/data/models/nbv/10-objects_SAC_mode1_100s_7200e_seed0.zip"  # to continue training

  val_num: ~  # validate every X episodes, if None: every time each object got trained
